server:
  port: 8088

allowed.origins: http://localhost:8080

adminPath: /api/v1
spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: postgres
          password: 123456
          url: jdbc:postgresql://localhost:5432/learn
          driver-class-name: org.postgresql.Driver

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl